install.packages('mlr3',dependencies = T)
install.packages('mlr3verse',dependencies = T)
install.packages('tidyverse',dependencies = T)
install.packages('eoffice',dependencies = T)
install.packages('openxlsx',dependencies = T)
install.packages('gtsummary',dependencies = T)
install.packages('rms',dependencies = T)
install.packages('do',dependencies = T)
install.packages('set',dependencies = T)
install.packages('base.rms',dependencies = T)
install.packages('pbapply',dependencies = T)
install.packages("R-package/ggDCA_1.1.tar.gz", repos = NULL, type = "source")
install.packages("R-package/mlr3extralearners-0.8.0.tar.gz", repos = NULL, type = "source")
install.packages("R-package/ResourceSelection_0.3-6.tar.gz", repos = NULL, type = "source")
install.packages('flextable',dependencies = T)
install.packages('precrec',dependencies = T)
install.packages('ggthemes',dependencies = T)
install.packages('precrec',dependencies = T)
install.packages('randomForest',dependencies = T)
install.packages('RWeka',dependencies = T)
install.packages('gbm',dependencies = T)
install.packages('xgboost',dependencies = T)
install.packages('e1071',dependencies = T)
install.packages('glmnet',dependencies = T)
install.packages('kknn',dependencies = T)
install.packages('shinythemes',dependencies = T)
